### ISSUE TITLE
Version fingerprinting

### ISSUE THREAD

**Issue by rosgos** [rastating/joomlavs#20]
Why don't you try to get the Joomla version of the file /administrator/manifests/files/joomla.xml before getting it from the README.txt? If the file is accessible, it will give you more accurate information about the version.

For example:
https://www.joomla.org/administrator/manifests/files/joomla.xml gives you 3.6.4 while https://www.joomla.org/README.txt gives you 3.6

**Comment by rastating** [comment]
Sorry for the late response, I have only just noticed this was open! Thanks for the information, I'll look at adding support for this at some point in the next week :+1:

**Comment by rastating** [comment]
I some how completely forgot about this _again_!

Just added support for the admin manifest and I have also made it the primary source to check, as it seems to be the most reliable.

Thanks again for the suggestion! :+1:

**Comment by rosgos** [comment]
That's good news.
Thanks to you for your time!
