### ISSUE TITLE
How to update the database list ?

### ISSUE THREAD

**Issue by X-HAT** [rastating/joomlavs#21]
Hello,

Can we update the database like wpscan ??    (wpscan.rb --update)

Thanks.

**Comment by rastating** [comment]
The list of vulnerabilities isn't maintained separately to the application currently, so at the moment, you need the latest version of the application to have the latest list.

Hopefully in the near future, I'll get chance to add an ```--update``` switch though.

**Comment by X-HAT** [comment]
Thank you.
