### ISSUE TITLE
Dependencies on Ubuntu

### ISSUE THREAD

**Issue by Dade88** [rastating/joomlavs#22]
I had some problems running JoomlAVS following installation instructions due to libcurl libraries, which were already installed.

Finally I solved the problem by following [WPScan instructions for Ubuntu Dependencies](https://github.com/wpscanteam/wpscan#installing-dependencies-on-ubuntu). Long story short: libcurl4-openssl-dev was missing.

Hope it can be helpful to anyone else.

**Comment by rastating** [comment]
Thanks for the information, I'll add it to the README :)
