### ISSUE TITLE
Error on symbolic link

### ISSUE THREAD

**Issue by maestroi** [rastating/joomlavs#23]
When symbolic link is used for this tool we get following error:

`/opt/joomlavs/lib/joomlavs/joomlavs.rb:33:in `read': No such file or directory @ rb_sysopen - data/joomla.json (Errno::ENOENT)
        from /opt/joomlavs/lib/joomlavs/joomlavs.rb:33:in `joomla_vulnerabilities'
        from /opt/joomlavs/lib/joomlavs/joomlavs.rb:47:in `display_joomla_vulns'
        from /usr/bin/joomlavs:83:in `start'
        from /usr/bin/joomlavs:94:in `<main>'`

The problem is it uses absolute path's.
i am not much of a ruby programmer but should be easy fix

**Comment by rastating** [comment]
Thanks for the report, will try to push an update for this later today :)

**Comment by rastating** [comment]
Hey @maestroi - just checked an update in that fixes this. Let me know if you run into any more issues with symlinks :)
