### ISSUE TITLE
joomla website via https

### ISSUE THREAD

**Issue by abroc** [rastating/joomlavs#31]
joomlavs didn't detect version and vulnerability via https, only via http was working.

Thanks,
Jan

**Comment by rastating** [comment]
What platform are you running on?

If you run the scan with Wireshark monitoring in the background, do the requests definitely lead you to the correct vhost?

**Comment by abroc** [comment]
Platform is Debian, but issue is in Typhoeus::Request.new. I just added these options and script was working like via HTTP.
     ssl_verifyhost: 0,
     ssl_verifypeer: false,

**Comment by rastating** [comment]
Thanks, I'll look into adding a CLI option to ignore certificate errors.

**Comment by rastating** [comment]
Better late than never - just pushed an update into `master` which will let you do scans without the TLS checks. To use it, run JoomlaVS with the `--disable-tls-checks` option :smile: 

Thanks again for the suggestion!
